- hosts: localhost
  gather_facts: no

  tasks:
    - name: Import common vars
      ansible.builtin.include_vars:
        file: vars.yml

    - name: "Clone VM from template"
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
        datacenter: "{{ vm_datacenter }}"
        cluster: "{{ vm_cluster }}"
        name: "{{ vm_name }}"
        template: "{{ template_name }}"
        folder: "{{ vm_folder }}"
        state: present
        networks:
          - name: "{{ vm_network_name }}"
            device_type: "vmxnet3"
            type: "dhcp"
        datastore: "{{ datastore_for_template_name }}"
        wait_for_ip_address: yes

    - name: "Power on the newly created VM"
      community.vmware.vmware_guest_powerstate:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
        datacenter: "{{ vm_datacenter }}"
        name: "{{ vm_name }}"
        state: powered-on

    - name: "Get VM details"
      community.vmware.vmware_vm_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
      register: vm_facts

    - name: "Display facts"
      debug:
        msg: "{{ vm_facts }}"

    - name: "Display VM IP Address"
      debug:
        msg: "The IP address of the VM is {{ vm_facts.virtual_machines[0].esxi_hostname }}"

    - name: "Set VM IP Address as fact"
      set_fact:
        vm_ip: "{{ vm_facts.virtual_machines[0].esxi_hostname }}"

    - name: "Add VM to the inventory"
      ansible.builtin.add_host:
        name: "{{ vm_ip }}"
        groups: new_vms

- hosts: new_vms
  tasks:
    - name: "Ping the new VM"
      ansible.builtin.ping:
